services:
  - type: web
    name: inventory-frontend
    env: static
    plan: free
    buildCommand: npm install --legacy-peer-deps && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: API_URL
        value: https://backdep.onrender.com
